
package presentacion;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Producto;


public class Productos extends javax.swing.JFrame {
    
      
    
  
    public Productos() {
        initComponents();
        Refrescar();
        
  
        
        
        jButton_consultar = new javax.swing.JButton();
    jButton_consultar.setText("Consultar");
        jButton_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultarActionPerformed(evt);
            }
        });
    }
    
    
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_guardar = new javax.swing.JButton();
        jButton_actualizar = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_consultar = new javax.swing.JButton();
        jButton_cerrar = new javax.swing.JButton();
        jLabelnombre = new javax.swing.JLabel();
        jLabelid = new javax.swing.JLabel();
        jLabeltemperatura = new javax.swing.JLabel();
        jLabelvalorbase = new javax.swing.JLabel();
        jTextField_textoN = new javax.swing.JTextField();
        jTextField_textoI = new javax.swing.JTextField();
        jTextField_textoT = new javax.swing.JTextField();
        jTextField_textoVB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Productos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Temperatura", "ValorBase"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });

        jButton_actualizar.setText("Actualizar");
        jButton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarActionPerformed(evt);
            }
        });

        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        jButton_consultar.setText("Consultar");
        jButton_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_consultarActionPerformed(evt);
            }
        });

        jButton_cerrar.setText("Cerrar");
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });

        jLabelnombre.setText("Nombre");

        jLabelid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelid.setText("Id");

        jLabeltemperatura.setText("Temperatura");

        jLabelvalorbase.setText("Valor Base");

        jTextField_textoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_textoNActionPerformed(evt);
            }
        });

        jTextField_textoI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_textoIActionPerformed(evt);
            }
        });

        jTextField_textoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_textoTActionPerformed(evt);
            }
        });

        jTextField_textoVB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_textoVBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelvalorbase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabeltemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addComponent(jLabelid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_textoI, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jTextField_textoT)
                            .addComponent(jTextField_textoVB)
                            .addComponent(jTextField_textoN)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_cerrar)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_cerrar)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_textoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_textoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelnombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeltemperatura)
                            .addComponent(jTextField_textoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelvalorbase)
                            .addComponent(jTextField_textoVB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_consultar)
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO add your handling code here:
        Producto miproducto = new Producto();
        String id = jTextField_textoI.getText();
        String nombre = jTextField_textoN.getText();
        double temperatura = Double.parseDouble(jTextField_textoT.getText());
        double valorBase = Double.parseDouble(jTextField_textoVB.getText());
        miproducto.setId(id);
        miproducto.setNombre(nombre);
        miproducto.setTemperatura(temperatura);
        miproducto.setValorBase(valorBase);
        if (miproducto.guardarProducto()) {
            JOptionPane.showMessageDialog(this, "Operacion realizada con éxito");
            
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar");
        }
        cleartext();
        
        
    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    private void jButton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarActionPerformed
        // TODO add your handling code here:

        Producto act_producto = new Producto();
        String txt_id = jTextField_textoI.getText();
        String txt_nombre = jTextField_textoN.getText();
        double txt_temperatura = Double.parseDouble(jTextField_textoT.getText());
        double txt_valorBase = Double.parseDouble(jTextField_textoVB.getText());
        act_producto.setId(txt_id);
        act_producto.setNombre(txt_nombre);
        act_producto.setTemperatura(txt_temperatura);
        act_producto.setValorBase(txt_valorBase);
        if (act_producto.actualizarProducto()) {
            JOptionPane.showMessageDialog(this, "Operacion realizada con éxito");
           
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar");
        }
         cleartext();
         Refrescar();
                  
        
    }//GEN-LAST:event_jButton_actualizarActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        String tbl_id = jTable1.getValueAt(fila, 0).toString();
        Producto borra_producto = new Producto();
        borra_producto.setId(tbl_id);
       System.out.println(tbl_id);
        if (borra_producto.borrarProducto()) {
            JOptionPane.showMessageDialog(this, "Operacion realizada con éxito");
           cleartext();
        } else {
            JOptionPane.showMessageDialog(this, "Operacion fallida");
        }
         cleartext();
         
                        
        
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_consultarActionPerformed
        // TODO add your handling code here:
        Refrescar();
    } 
    public void Refrescar(){
       
        Object[][] rowData = new Object[1][5];
        Object[] miscolumnas = {"Id","Nombre","Temperatura", "valorBase", "costo"};
        DefaultTableModel mimodelo = new DefaultTableModel();
        mimodelo.setColumnIdentifiers(miscolumnas);
        jTable1.setModel(mimodelo);
        Producto p = new Producto();
        List<Producto> lista = p.listarProducto();
        for (Producto pro : lista) {
            rowData[0][0] = pro.getId();
            rowData[0][1] = pro.getNombre();
            rowData[0][2] = pro.getTemperatura();
            rowData[0][3] = pro.getValorBase();
            if (pro.getTemperatura()>20) {rowData[0][4] = pro.getValorBase()*(1.1f);}
            else {rowData[0][4] = pro.getValorBase()* (1.2f);}
            rowData[0][4]=String.format("%.2f", rowData[0][4]);
            mimodelo.addRow(rowData[0]);
        
        } 
        cleartext();
      
            
                        
    }//GEN-LAST:event_jButton_consultarActionPerformed

    private void jTextField_textoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_textoNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_textoNActionPerformed

    private void jTextField_textoIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_textoIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_textoIActionPerformed

    private void jTextField_textoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_textoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_textoTActionPerformed

    private void jTextField_textoVBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_textoVBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_textoVBActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        String tbl_id = jTable1.getValueAt(fila, 0).toString();
        String tbl_nombre = jTable1.getValueAt(fila, 1).toString();
        String tbl_temperatura_s = jTable1.getValueAt(fila, 2).toString();
        String tbl_valorBase_s = jTable1.getValueAt(fila, 3).toString();
        //PASAR LAS CADENAS A DOBLE (TEMPERATURA, VALOR)
        Double tbl_temperatura = Double.parseDouble(tbl_temperatura_s);
        Double tbl_valorBase = Double.parseDouble(tbl_valorBase_s);
        // PASA LOS DATOS DE LAS VARIABLES A LOS JTEXTFIELD
        jTextField_textoI.setText(tbl_id);
        jTextField_textoN.setText(tbl_nombre);
        jTextField_textoT.setText(tbl_temperatura_s);
        jTextField_textoVB.setText(tbl_valorBase_s);
    }//GEN-LAST:event_jTable1MouseClicked
 
    //VACIAR TEXTO DE CAJAS//
    public void cleartext(){
     jTextField_textoI.setText("");
        jTextField_textoN.setText("");
        jTextField_textoT.setText("");
        jTextField_textoVB.setText("");
 }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_actualizar;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JButton jButton_consultar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JLabel jLabelnombre;
    private javax.swing.JLabel jLabeltemperatura;
    private javax.swing.JLabel jLabelvalorbase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_textoI;
    private javax.swing.JTextField jTextField_textoN;
    private javax.swing.JTextField jTextField_textoT;
    private javax.swing.JTextField jTextField_textoVB;
    // End of variables declaration//GEN-END:variables
}
